deployment:
  mode: decoupled
  role: "control_plane" 
  role_control_plane:
      config_provider: etcd
  etcd:
     host:
         - http://${etcd_IP}:${etcd_Port}
     prefix: /apisix
     timeout: 30
  # # -- used for control_plane deployment mode
  # controlPlane:
  #   # -- conf Server address
  #   confServerPort: "9280"
    # -- secret name used by conf Server
    # certsSecret: "cp-secret"
    # # -- conf Server CA cert name
    # cert: "tls.crt"
    # # -- conf Server cert key name
    # certKey: "tls.key"

  # -- certs used for certificates in decoupled mode
  # certs:
  #   # -- secret name used for decoupled mode
  #   certsSecret: "client-secret"
  #   # -- cert name in certsSecret
  #   cert: "tls.crt"
  #   # -- cert key in certsSecret
  #   cert_key: "tls.key"
 
  #   # -- trusted_ca_cert name in certsSecret
  #   mTLSCACertSecret: "ca-secret"
  #   # -- mTLS CA cert filename in mTLSCACertSecret
  #   mTLSCACert: "ca.pem"    
#END
