deployment:
   mode: decoupled
   role: "data_plane"
   role_data_plane:
     config_provider: etcd
       
   dataPlane:
     controlPlane:
       host: ["https://apisix-control-plane.apisix.svc:9280"]
 etcd:
   # -- install etcd(v3) by default, set false if do not want to install etcd(v3) together
   enabled: false            
#END
