apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: dashboard-gateway
 labels:
    app.kubernetes.io/instance: apisix-cp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 3.10.0
    helm.sh/chart: apisix-2.9.0
spec:
 selector:
   istio: ingressgateway # use istio default controller
 servers:
 - port:
     number: 80
     name: http
     protocol: HTTP
   hosts:
   - loclahost
   # tls:
   #   httpsRedirect: true
 # - port:
 #     number: 443
 #     name: https
 #     protocol: HTTPS
 #   hosts:
 #   - {{ .Values.hostname }}
 #   tls:
 #     mode: SIMPLE
 #     credentialName: {{ .Values.tlsCredentialName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dashboard-vs
spec:
  hosts:
  - localhost
  gateways:
  - dashboard-gateway
  http:
  - match: 
    - uri:
        prefix: /    
    route:
    - destination:
        host: apisix-cp-dashboard
        port:
          number: 80
